# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-118363731-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Computer Science', path: 'menu', url: 'cs.html'}
- {name: 'Research', path: 'menu', url: 'research.html'}
- {name: 'Lifestyle', path: 'menu', url: 'lifestyle.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/ekote'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/esterakot/'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
